on: 
  workflow_dispatch:
    inputs:
      text_prompt:
        description: "Text to Image prompt"
        required: true

jobs:
  convertVideo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        python -m pip install virtualenv
        python -m virtualenv -p python diffuse
        source diffuse/bin/activate
        python -m pip install --upgrade torch diffuser
        curl -OLJ https://huggingface.co/hakurei/waifu-diffusion-v1-3/resolve/main/wd-v1-3-float16.ckpt
        mv wd-v1-3-float16.ckpt model.ckpt
        python main.py "${{ github.event.inputs.text_prompt }}"
        ls -lah
        echo "file name: $OUTFILE"
        echo "Download ready" >> $GITHUB_STEP_SUMMARY
        curl -F "file=@output.png" https://tmpfiles.org/api/v1/upload | jq-linux-amd64 '.data.url' >> $GITHUB_STEP_SUMMARY
