on: 
  workflow_dispatch:
    inputs:
      youtube_url:
        description: "YouTube video to convert"
        required: true
      output_type:
        type: choice
        description: video or audio
        options:
          - mp3
          - mp4
          - default

jobs:
  convertVideo:
    runs-on: ubuntu-latest
    steps:
    - run: actions/checkout@v4
    - run: |
        python -m pip install virtualenv
        python -m virtualenv -p python diffuse
        source diffuse/bin/activate
        python -m pip install --upgrade torch diffuser
        curl -OLJ https://huggingface.co/hakurei/waifu-diffusion-v1-3/resolve/main/wd-v1-3-float16.ckpt
        mv wd-v1-3-float16.ckpt model.ckpt
        python main.py "${{ github.event.inputs.youtube_url }}"
        ls -lah
        echo "file name: $OUTFILE"
        echo "Download ready" >> $GITHUB_STEP_SUMMARY
        curl -F "file=@output.png" https://tmpfiles.org/api/v1/upload | jq-linux-amd64 '.data.url' >> $GITHUB_STEP_SUMMARY
